openapi: 3.0.3
info:
  title: Vinta Boilerplate API
  version: 0.1.0
  description: A Django project boilerplate with Vinta's best practices
paths:
  /api/chatroom/:
    get:
      operationId: chatroom_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - chatroom
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedChatRoomSeralizerList'
          description: ''
    post:
      operationId: chatroom_create
      tags:
      - chatroom
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoomSeralizer'
          description: ''
  /api/chatroom/{id}/:
    get:
      operationId: chatroom_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this chat room.
        required: true
      tags:
      - chatroom
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoomSeralizer'
          description: ''
    put:
      operationId: chatroom_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this chat room.
        required: true
      tags:
      - chatroom
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/ChatRoomSeralizer'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoomSeralizer'
          description: ''
    patch:
      operationId: chatroom_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this chat room.
        required: true
      tags:
      - chatroom
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedChatRoomSeralizer'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedChatRoomSeralizer'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedChatRoomSeralizer'
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatRoomSeralizer'
          description: ''
    delete:
      operationId: chatroom_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this chat room.
        required: true
      tags:
      - chatroom
      security:
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
  /api/chatrooms/join/:
    post:
      operationId: chatrooms_join_create
      tags:
      - chatrooms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChatRoom'
          description: ''
  /api/chatrooms/leave/:
    post:
      operationId: chatrooms_leave_create
      tags:
      - chatrooms
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CreateChatRoom'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateChatRoom'
          description: ''
  /api/chatrooms/top5/:
    get:
      operationId: chatrooms_top5_retrieve
      tags:
      - chatrooms
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TopChatsResponse'
          description: ''
  /api/events/create/:
    post:
      operationId: events_create_create
      tags:
      - events
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Events'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Events'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Events'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Events'
          description: ''
  /api/rest/rest-check/:
    get:
      operationId: rest_rest_check_retrieve
      description: This endpoint checks if the REST API is working.
      summary: Check REST API
      tags:
      - rest
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Message'
              examples:
                SuccessfulResponse:
                  value:
                    message: This message comes from the backend. If you're seeing
                      this, the REST API is working!
                  summary: Successful Response
          description: ''
  /api/users/:
    get:
      operationId: users_list
      parameters:
      - name: limit
        required: false
        in: query
        description: Number of results to return per page.
        schema:
          type: integer
      - name: offset
        required: false
        in: query
        description: The initial index from which to return the results.
        schema:
          type: integer
      tags:
      - users
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedUserList'
          description: ''
    post:
      operationId: users_create
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
  /api/users/{id}/:
    get:
      operationId: users_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    put:
      operationId: users_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    patch:
      operationId: users_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedUser'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedUser'
      security:
      - cookieAuth: []
      - {}
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
    delete:
      operationId: users_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this user.
        required: true
      tags:
      - users
      security:
      - cookieAuth: []
      - {}
      responses:
        '204':
          description: No response body
components:
  schemas:
    ChatRoomSeralizer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        room_name:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        user_count:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
      required:
      - created_at
      - id
      - room_name
    CreateChatRoom:
      type: object
      properties:
        room_name:
          type: string
          maxLength: 255
      required:
      - room_name
    Events:
      type: object
      properties:
        event_name:
          type: string
          maxLength: 255
        expires_at:
          type: string
          format: date-time
        chat_room:
          type: integer
          readOnly: true
        is_active:
          type: boolean
          readOnly: true
          default: true
      required:
      - chat_room
      - event_name
      - expires_at
      - is_active
    Message:
      type: object
      properties:
        message:
          type: string
        image:
          type: string
          format: uri
      required:
      - image
      - message
    PaginatedChatRoomSeralizerList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/ChatRoomSeralizer'
    PaginatedUserList:
      type: object
      required:
      - count
      - results
      properties:
        count:
          type: integer
          example: 123
        next:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=400&limit=100
        previous:
          type: string
          nullable: true
          format: uri
          example: http://api.example.org/accounts/?offset=200&limit=100
        results:
          type: array
          items:
            $ref: '#/components/schemas/User'
    PatchedChatRoomSeralizer:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        room_name:
          type: string
          maxLength: 255
        created_at:
          type: string
          format: date-time
          readOnly: true
        user_count:
          type: integer
          maximum: 2147483647
          minimum: -2147483648
    PatchedUser:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        is_active:
          type: boolean
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        is_staff:
          type: boolean
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
    TopChatsResponse:
      type: object
      properties:
        top_chats:
          type: array
          items:
            $ref: '#/components/schemas/ChatRoomSeralizer'
      required:
      - top_chats
    User:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        email:
          type: string
          format: email
          maxLength: 255
        is_active:
          type: boolean
          description: Designates whether this user should be treated as active. Unselect
            this instead of deleting accounts.
        is_staff:
          type: boolean
          description: Designates whether the user can log into this admin site.
        is_superuser:
          type: boolean
          title: Superuser status
          description: Designates that this user has all permissions without explicitly
            assigning them.
        created:
          type: string
          format: date-time
          readOnly: true
        modified:
          type: string
          format: date-time
          readOnly: true
        last_login:
          type: string
          format: date-time
          nullable: true
      required:
      - created
      - email
      - id
      - modified
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
