# Generated by Django 5.1.2 on 2024-10-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='user_count',
            field=models.IntegerField(default=0),
        ),
    ]
