# Generated by Django 5.1.2 on 2024-10-10 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatroom', '0002_chatroom_user_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='user_count',
            field=models.IntegerField(default=1),
        ),
    ]
